### ISSUE TITLE
[Research] Wallet: Support AWS and Azure Key Managers

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-wallet-headless#147]
UPDATE: This issue was turned into a research issue, while we decide the best way forward (see https://github.com/HathorNetwork/hathor-wallet-headless/issues/147#issuecomment-1038663430)

A new issue will hold the actual design: https://github.com/HathorNetwork/hathor-wallet-headless/issues/148

---------------
# Summary

Add support to start a wallet using [AWS Key Management Service](https://aws.amazon.com/kms/) and [Azure Key Vault](https://azure.microsoft.com/en-us/services/key-vault/).

# Motivation

Securely storing a seed might be very challenging for use cases. As the seed must be stored on the server running the wallet, maintenance tasks might expose the seed to engineers who would not have access to them. In this scenario, using a trusted service as KMS or Key Vault might simplify processes and give better protection to the seed.

# Notes

a) Notice that the wallet need an xpub to be able to load properly.
b) The signature will be executed by the KMS or Key Vault, i.e., the wallet will never have access to the seed and the xpriv themselves.

# Acceptance Criteria

1. Explain how the wallet will be configured to use one of these key management services.
2. Detail the common flows of the wallet (and any limitation that might appear): (i) loading, (ii) generating addresses, (iii) detecting new transactions, and (iv) generating transactions.
3. Check compatibility with Hathor Wallet API and Hathor Wallet Service.
4. Check compatibility with multisig.
5. Benchmark with other wallets that support KMS or Key Vault.

**Comment by luislhl** [comment]
I've spent some time researching some possibilities and limitations regarding the problem that I think should be discussed and validated before I'm able to go on with this design.

I'll be referring to both AWS KMS and Azure Key Vault (and any other similar service) as just Vaults.

# Objective
The objective I had in mind, besides what is already described in the main description, is that we should be able to generate a Private Key in the Vault, and be able to perform all the operations needed by the wallet, **without ever needing the Private Key to be outside of the Vault.**

A good analogy would be Ledger. But instead of a physical device, we would have a cloud service doing the same thing for us.

Since our wallet was built as a Hierarchical Deterministic Wallet (as described by BIP32), these are the basic operations that would need to be performed using the Private Key:
1. Generate a Public Key
2. Sign
3. Derive child Private Keys and Public Keys according to BIP32

# Supported Operations
The Vaults do have support for generating ECDSA using the `secp256k1` curve, which is exactly what we need.

So it is easy to generate such a key, get its Public Key and sign data using it. [1]

However, I couldn't find a way to make them derive keys to support the HD wallet.

Since key derivation is an operation that needs access to the private keys (at least to derive other private keys, AFAIK), it is something that would need to be supported inside the service.

# Hardware Security Modules
By digging further on how those Vaults work under the hood, I found out that they use something called HSM, or Hardware Security Modules.

These are devices designed to safeguard cryptographic keys and allow cryptographic operations to be performed with them. So the Vaults are just abstractions to provision and manage HSMs for us in a nice way.

AWS allow us to provision and use the HSMs directly, without KMS as an intermediary, by using AWS CloudHSM service.

I've looked into whether we could have more possibilities by using the HSM directly

There is a standard for cryptographic operations called PKCS 11 which most HSMs support. Its specification can be found in https://docs.oasis-open.org/pkcs11/pkcs11-base/v3.0/cos01/pkcs11-base-v3.0-cos01.html#_Toc29976707

Here we can see which of those operations are supported by AWS CloudHSM: https://docs.aws.amazon.com/cloudhsm/latest/userguide/pkcs11-apis.html

The only operation in this list that could give us what we need was the `C_DeriveKey`. However, the only derivation mechanisms supported by CloudHSM are `CKM_ECDH1_DERIVE` and `CKM_SP800_108_COUNTER_KDF` [2], and they are not what we need for BIP32.

# Possibilities for further investigation
- Find other services offering HSMs in the Cloud that could support BIP32 key derivation

# Reference
[1] AWS KMS supported operations: https://docs.aws.amazon.com/pt_br/kms/latest/APIReference/API_Operations.html
[2] AWS CloudHSM derivation mechanisms: https://docs.aws.amazon.com/cloudhsm/latest/userguide/pkcs11-mechanisms.html

**Comment by msbrogli** [comment]
Hi @luislhl . Great research and comment. Thanks! Let me add some thoughts.

> I could be wrong and there is a way to derive keys using KMS/Key Vault after all.

I feel you are right. They will generally not natively support HD Wallets. I'm happy that you found Luna.

> We could try other Cloud vendors, like Luna (or find others), that support BIP32 derivation. However, this could be not ideal for some partners, and even for us. The costs are also still not clear.

I'm not sure whether they would trust Luna. Anyway, it seems like one branch of development: Integrate with Luna and others that support BIP32 derivation.

> We could make our wallet work in a non-HD fashion when used with AWS KMS. We would just generate a bunch of Private Keys and their Public Keys, and use them as addresses. This may not be ideal as well, and would probably require greater changes in the code.

I feel that's the way other are doing it. Do we have a way to enumerate the key generation? If yes, I feel the change in the wallet is not complex. We would need to have an async method that signs the transactions using the i-th key, and it would have a specific implementation for each type of wallet. What do you think?

> We could have a different process, where the Private Key is generated locally and we use it to derive other keys, then just use a regular KMS key to encrypt/decrypt the Private Keys as needed. We would need to backup them somehow as well. This would mean a lower level of security.

I don't feel it's safe enough since the xpriv will be available in the wallet's memory. I think we can discard this choice.

> We could also try to find some Cloud Service that supports importing the key, which would be generated locally. This would also mean a lower level of security, and finding a service like this may be hard.

I don't feel it's safe enough since the key generation is a critical step in the overall security of wallets. I think we can discard this choice as well.

> I have also stumbled upon something called MPC that can be used to protect keys, but didn't really looked it deeply, since it looked more complex and potentially we would also have problems with key derivation: https://www.fireblocks.com/what-is-mpc/

I like MPC but each part must individually keep a secret protect. It might be a good alternative and I feel we should discuss it further.

**Comment by luislhl** [comment]
Thanks for the feeback, @msbrogli !

> I feel that's the way others are doing it. Do we have a way to enumerate the key generation? If yes, I feel the change in the wallet is not complex. We would need to have an async method that signs the transactions using the i-th key, and it would have a specific implementation for each type of wallet. What do you think?

Seems like a good path. I've testes whether we can enumerate the keys with KMS, and it's possible by giving them `aliases`, then retrieving them using their `alias`.

This is a gist demonstrating this:
https://gist.github.com/luislhl/54f307d45499228b461a2ba3c0032517

I would still need to make sure Azure supports something like this as well, but in the worst of cases we would have at least KMS.

-----------
Apart from this, I think we just need to decide what to include in this design initially, since we have 3 possibilities here that are not exclusive:
1. Use AWS KMS in a non-HD fashion
2. Integrate with Luna and/or Kaleido (possibly others)
3. Take a deeper look into MPC

Do you think we could focus on point 1 at a first moment?

**Comment by msbrogli** [comment]
I feel we are good with this initial research and we should look for data points to support the next steps. I'll check with Gama and the bizdev team which use cases would benefit from this feature and understand which next steps fits better with their needs.

**Comment by obiyankenobi** [comment]
The 2 use cases I know which have mentioned this are:

1. TK3000
At the moment, they are using Parfin. We'd need to understand if a solution like we are proposing (`#1`) would fit their needs. It's not clear to me how this woud function on the management side. They probably have a complex backoffice.

2. OnePercent
They were the ones who originally mentioned Azure key management. We could check with them how their solution works, if there's any way to keep the HD wallets.

I believe it's better to get feedback from them first. Otherwise, I'm afraid we can design and implement something that won't be used. Most projects seem inclined to use a custodian such as Fireblocks, BitGo or Parfin. Would they use a solution as ours?
