### ISSUE TITLE
Design: Add support for multiple wallets

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet-headless#6]
## Problem

People want to handle multiple wallets from a single API server.

## Description

Imagine an app with many users and, when they sign up (with email and password) the app owner creates a wallet for each one of them. Every time they login, the wallet is loaded in the API, so the app can call endpoints to execute actions with it. So the API will have many wallet objects (one for each logged user) and, when executing any request, it would require a reference for each wallet the request is directed.

I agree that we can replace the `/0`, `/1`, `/2` by a key for each user. These keys will have to be stored somewhere and dynamically loaded and unloaded into memory, i.e., the HTTP API should also have a load/unload endpoint.

I think there are multiple ways to run multiple wallets. So, we may need more data points to decide which one is the best for each use case. For instance, a solution to run only a bunch of wallets is possibly different from a solution to run millions of wallets.

If the number of wallets is high, the use case may consider to partite the wallets in shards running on different wallet instances.

### One seed at all

In this case, the app can associate a list of addresses for each user. I believe that most exchanges do it for deposits. Users open the deposit page and get an address. That address is generated using a single seed, and it is associated to the user in a separate database.

Changing the seed is simple because new addresses would be associated to the users. So, the app should store the pair `(seed_id, address)` for each user.

Pros: There is only one seed to be securely stored and managed.

Cons: If the seed is leaked, all addresses would be exposed. So, another measures such as internally transfer the funds to other vaults may be necessary. The app may have to increase the `GAP_LIMIT`. The app is responsible for not mixing addresses, i.e., more responsibility and complexity in the app.

### One seed with multiple passphrases

In this case, the app can generate a passphrase for each user and store the passphrase in a separate database.

Maybe the app should support more than one passphrase by user to be able to change the passphrase in the future.

This wallet can support it using the prefix as passphrase. So, instead of `/0`, `/1`, `/2`, the API would receive `/passphrase` or `/passphrase_id` as prefix. So, the wallet can dynamically load any user balance generating its addresses only when requested.

**TODO** Is it possible to create an xpub (or an intermediate structure) which supports changing the passphrase in real time? I think it is possible, but we should double check it. If not, this method may not allow the wallet to run in read-only mode.

Pros: There is only one seed to be securely stored and managed. Even if this seed is leaked, the passphrases would be necessary to get access to the funds.

Cons:

### One seed with multiple accounts using different paths

This approach is BIP32 compatible. It is similar to using one seed with multiple passphrases.

Pros:

Cons: Anyone with the seed can scan the balances.

### Multiple seeds

In this case, the app should have a persistent storage to securely keep the seeds.

Pros: If one seed leaks, it will affect only one user.

Cons: You need more storage to keep all seeds, even the ones that have never been used by users.

## API for multiple wallets

Add two endpoints `/key/start` and `/key/stop`.

### `/key/start`

This endpoints starts a new wallet for the given key (unless it has already been started).

### `/key/stop`

This endpoint stops the wallet associated with the given key.

### `/key/status`

This endpoints returns the status of the wallet with the given key.

## Decision

For now we will support having a single seed with multiple passphrases, where each passphrase will store a wallet object. This wallet instance will be started/stopped with the corresponding new APIs for multiple wallets.

**Comment by msbrogli** [comment]
I think we should work on a more detailed description of the problem and possible solutions. Than, we can dive deep into one of the solutions and implement it.

**Comment by msbrogli** [comment]
We can easily use the `/0`, `/1`, `/2` prefix to do it. Each prefix is related to a different wallet. It can be either sequential or random. Each wallet may be individually enabled, which means it will sync and be ready to be used.

I think we should think in a scalable solution. Using current implementation, it would require at least `20*k` address subscriptions per wallet, and it doesn't seem to work when `k` is large enough.

Maybe we should improve our wallet API in the full-node to support xpub keys (maybe using bloom filters to improve privacy). We can also turn this index server into a separate service, which would allow the indexes to be partitioned among many servers.

After all, I think we should dive deep into the problem and possible solutions in a specific design that may affect all our wallets, improving both performance and scalability.

**Comment by pedroferreira1** [comment]
**Problem:**

People want to handle multiple wallets from a single API server.

**Description:**

Imagine an app with many users and, when they sign up (with email and password) the app owner creates a wallet for each one of them. Every time they login, the wallet is loaded in the API, so the app can call endpoints to execute actions with it. So the API will have many wallet objects (one for each logged user) and, when executing any request, it would require a reference for each wallet the request is directed.

**Solution:**

 We could use `/0/`, `/1/`, `/2/` but this would require the app owner to know what index corresponds to each wallet. That's why I thought we could expect as parameter a 'key' that is what the app knows about the user who has the wallet. This 'key' would be passed as parameter when loading the wallet also.

**Comment by pedroferreira1** [comment]
I agree about the API refactor to have a scalable solution, however this is a problem we currently have. If we have enough users downloading and using our desktop wallet we would have this problem already. Maybe we should create an issue about it to discuss this API refactor?

**Comment by msbrogli** [comment]
I agree that we can replace the `/0`, `/1`, `/2` by a key for each user. These keys will have to be stored somewhere and dynamically loaded and unloaded into memory, i.e., the HTTP API should also have a load/unload endpoint.

I think there are multiple ways to run multiple wallets. So, we may need more data points to decide which one is the best for each use case. For instance, a solution to run only a bunch of wallets is possibly different from a solution to run millions of wallets.

If the number of wallets is high, the use case may consider to partite the wallets in shards running on different wallet instances.

## Solutions

### One seed at all

In this case, the app can associate a list of addresses for each user. I believe that most exchanges do it for deposits. Users open the deposit page and get an address. That address is generated using a single seed, and it is associated to the user in a separate database.

Changing the seed is simple because new addresses would be associated to the users. So, the app should store the pair `(seed_id, address)` for each user.

Pros: There is only one seed to be securely stored and managed.

Cons: If the seed is leaked, all addresses would be exposed. So, another measures such as internally transfer the funds to other vaults may be necessary. The app may have to increase the `GAP_LIMIT`.

### One seed with multiple passphrases

In this case, the app can generate a passphrase for each user and store the passphrase in a separate database.

Maybe the app should support more than one passphrase by user to be able to change the passphrase in the future.

This wallet can support it using the prefix as passphrase. So, instead of `/0`, `/1`, `/2`, the API would receive `/passphrase` or `/passphrase_id` as prefix. So, the wallet can dynamically load any user balance generating its addresses only when requested.

**TODO** Is it possible to create an xpub (or an intermediate structure) which supports changing the passphrase in real time? I think it is possible, but we should double check it. If not, this method may not allow the wallet to run in read-only mode.

Prop: There is only one seed to be securely stored and managed. Even if this seed is leaked, the passphrases would be necessary to get access to the funds.

Cons:

### Multiple seeds

In this case, the app should have a persistent storage to securely keep the seeds.

Pros: If one seed leaks, it will affect only one user.

Cons: You need more storage to keep all seeds, even the ones that have never been used by users.

## Conclusion

Current implementation allows use cases to use "one seed at all". Adding support for "one seed with multiple passphrases" seems simple as well, but we would include an API to load/unload passphrases, or use an LRU approach do dynamically load/unload wallets.

After the "one seed with multiple wallets" is supported, it seems simple to add support for "multiple seeds", but we need to carefully discuss the persistent storage of the seeds.

Maybe we should add support for all these types and let the app choose the type in the config file.

Maybe we should consider creating a seed server, which would be used by this wallet to get, put, and generate seeds.

**Comment by obiyankenobi** [comment]
> We could use /0/, /1/, /2/ but this would require the app owner to know what index corresponds to each wallet. That's why I thought we could expect as parameter a 'key' that is what the app knows about the user who has the wallet. This 'key' would be passed as parameter when loading the wallet also.

I don't know if it's much different knowing the index or this key that you proposed. In that sense, I think the solutions are not very different.

I guess we have to consider if it's better having several wallet objects or just one, using the different indexes. It seems the first option is easier to implement, as everything is already set up when we create the wallet (load transactions, subscribe to addresses, etc).

The index approach seems a bit better, though, as we'd have just one connection to the server and we could save also on storage on the wallet side. If we go with it, we'd also have to implement some logic to tell from which index each transaction belongs, when a new tx arrives on the network. Definitely there's a bit more work with this approach.

**Comment by msbrogli** [comment]
@obiyankenobi I think we don't have to keep track of "which index each transaction belongs" because they will be on different `HathorWallet` instances. So, each wallet will keep its own transaction list.

**Comment by obiyankenobi** [comment]
I was suggesting to just have one wallet to handle all of it, since it shares the seed phrase. That's why I mentioned that it'd take more work. If we have one wallet per index, it's basically the same as the key idea.

**Comment by pedroferreira1** [comment]
We first need to define what a wallet is. For me it's impossible to have only one wallet and use many indexes. Each index in the HD path will generate a different private key, so for me, if we use this approach, we should have a different wallet for each index. 

> I don't know if it's much different knowing the index or this key that you proposed. In that sense, I think the solutions are not very different.

@obiyankenobi it's different because if we allow the user to define any key, they could use the user email, for instance, so they already have the email associated with 24 words and, every time they send a request they just send the email as the 'key' and the wallet headless knows which wallet it belongs.

But thinking more about the solution I like having different indexes and not having different seeds for each wallet. I still think we should support both cases in the wallet headless but specific about this use case, I feel the indexes are more interesting and easier to handle.

> Maybe we should consider creating a seed server, which would be used by this wallet to get, put, and generate seeds.

@msbrogli this is one of the requirements of this use case but only to generate a new seed (https://github.com/HathorNetwork/hathor-wallet-headless/pull/8). They would store the seeds in their own storage.

**Comment by obiyankenobi** [comment]
> @obiyankenobi it's different because if we allow the user to define any key, they could use the user email, for instance, so they already have the email associated with 24 words and, every time they send a request they just send the email as the 'key' and the wallet headless knows which wallet it belongs.

I don't understand your point. I think the same could be achieved with the index. If they have one index for each user, they just need to send the index and the wallet headless knows which wallet it should use. The difference is that they don't need to have one seed per user, just one index.

> We first need to define what a wallet is. For me it's impossible to have only one wallet and use many indexes. Each index in the HD path will generate a different private key, so for me, if we use this approach, we should have a different wallet for each index.

In the beginning I thought we could adapt the wallet to handle all indexes, but I guess it's better to keep it separated, 1 wallet each.

One potential problem with using just the indexes is that if the seed leaks, everyone's tokens can be stolen. We could have the passphrase instead of the index, so there's separation between wallets' funds.

**Comment by msbrogli** [comment]
@pedroferreira1 Approved.
